<?php
require_once __DIR__.'/../includes/header.php';
require_once __DIR__.'/../includes/pdf_generator.php';
checkAuth(['recepcion','admin']);
$db=getDBConnection();
$mesaId=(int)($_GET['mesa']??0);
$s=$db->prepare('SELECT * FROM mesas WHERE id=? AND activa=1');$s->execute([$mesaId]);$mesa=$s->fetch();if(!$mesa)die('Mesa no válida.');
$s=$db->prepare("SELECT * FROM comandas WHERE mesa_id=? AND estado='abierta'");$s->execute([$mesaId]);$comanda=$s->fetch();$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(isset($_POST['abrir'])&&!$comanda){$s=$db->prepare("INSERT INTO comandas(mesa_id,estado,fecha_apertura,usuario_apertura) VALUES(?,'abierta',?,?)");$s->execute([$mesaId,now(),$_SESSION['usuario']['id']]);$s=$db->prepare('SELECT * FROM comandas WHERE id=?');$s->execute([$db->lastInsertId()]);$comanda=$s->fetch();$db->prepare("UPDATE mesas SET estado='ocupada' WHERE id=?")->execute([$mesaId]);}
 elseif(isset($_POST['add'])&&$comanda){$pid=(int)$_POST['plato_id'];$qty=(float)$_POST['cantidad'];$p=$db->prepare('SELECT * FROM platos WHERE id=? AND activo=1');$p->execute([$pid]);$pl=$p->fetch();if($pl&&$qty>0){$db->prepare('INSERT INTO comanda_detalles(comanda_id,plato_id,cantidad,precio_unitario,notas) VALUES(?,?,?,?,?)')->execute([$comanda['id'],$pid,$qty,$pl['precio_cup'],trim($_POST['notas'])]);$msg='Producto añadido a la mesa.';}}
 elseif(isset($_POST['cobrar'])&&$comanda){
  $itemsStmt=$db->prepare('SELECT d.*,p.nombre FROM comanda_detalles d JOIN platos p ON p.id=d.plato_id WHERE d.comanda_id=? ORDER BY d.id');$itemsStmt->execute([$comanda['id']]);$items=$itemsStmt->fetchAll();$total=0.0;foreach($items as $it)$total+=(float)$it['cantidad']*(float)$it['precio_unitario'];
  $currency=$_POST['moneda'];$amount=numberValue($_POST['monto']??0);$method=$_POST['metodo']??'efectivo';$config=getAppConfig();$cup=convertToCUP($amount,$currency,$config);$requiredInCurrency=fromCUP((float)$total,$currency,$config);$change=max(0.0,$amount-$requiredInCurrency);
  if($total<=0)$msg='No se puede cobrar una comanda vacía.';elseif($amount<=0)$msg='Introduzca el monto recibido.';elseif($method==='efectivo' && $cup+0.01 < $total)$msg='El efectivo recibido es insuficiente. Total: '.money((float)$total).'.';elseif($method!=='efectivo' && abs($cup-$total)>0.01)$msg='El monto de la transferencia no coincide con el total.';else{
   $db->beginTransaction();
   try{
    $invoiceNumber=nextNumber('FACT-');$receiptNumber=nextNumber('COMP-');$lines=['Mesa: '.$mesa['numero'],'Método: '.strtoupper($method),'Moneda recibida: '.$currency,'Monto recibido: '.money($amount,$currency),'Total en CUP: '.money((float)$total),'Vuelto: '.money($change,$currency)];foreach($items as $it)$lines[]=$it['nombre'].' x '.$it['cantidad'].' · '.money($it['cantidad']*$it['precio_unitario']);
    $invoicePath=generarDocumentoPDF('factura',$invoiceNumber,'Factura de venta',$lines);$receiptPath=generarComprobantePDF($receiptNumber,$config,$items,(float)$total,$currency,$amount,$change,$method,(string)$mesa['numero']);
    $ins=$db->prepare('INSERT INTO facturas(numero,comanda_id,tipo,monto_total_cup,moneda,monto_moneda,metodo_pago,pdf_path,fecha,usuario_id) VALUES(?,?,?,?,?,?,?,?,?,?)');
    $ins->execute([$invoiceNumber,$comanda['id'],'factura',(float)$total,$currency,$amount,$method,$invoicePath,now(),$_SESSION['usuario']['id']]);$invoiceId=$db->lastInsertId();
    $ins->execute([$receiptNumber,$comanda['id'],'comprobante',(float)$total,$currency,$amount,$method,$receiptPath,now(),$_SESSION['usuario']['id']]);$receiptId=$db->lastInsertId();
    $db->prepare('INSERT INTO pagos(factura_id,metodo,moneda,monto,monto_cup,referencia,fecha,usuario_id) VALUES(?,?,?,?,?,?,?,?)')->execute([$receiptId,$method,$currency,$amount,$cup,trim($_POST['referencia']),now(),$_SESSION['usuario']['id']]);
    $open=$db->query("SELECT * FROM cajas WHERE estado='abierta' ORDER BY id DESC LIMIT 1")->fetch();
    if($open&&$method==='efectivo')$db->prepare("INSERT INTO movimientos_caja(caja_id,tipo,concepto,monto_cup,fecha,usuario_id) VALUES(?,'venta',?,?,?,?)")->execute([$open['id'],'Venta '.$receiptNumber,$total,now(),$_SESSION['usuario']['id']]);
    if($method==='transferencia'){$bank=$db->query('SELECT id FROM banco_cuentas WHERE activa=1 ORDER BY id LIMIT 1')->fetch();if($bank){$db->prepare("INSERT INTO banco_movimientos(cuenta_id,tipo,concepto,monto_cup,referencia,fecha,usuario_id) VALUES(?,'entrada',?,?,?,?,?)")->execute([$bank['id'],'Venta '.$receiptNumber,$total,trim($_POST['referencia']),now(),$_SESSION['usuario']['id']]);$db->prepare('UPDATE banco_cuentas SET saldo_cup=saldo_cup+? WHERE id=?')->execute([$total,$bank['id']]);}}
    $db->prepare("UPDATE comandas SET estado='pagada',fecha_cierre=?,usuario_cierre=? WHERE id=?")->execute([now(),$_SESSION['usuario']['id'],$comanda['id']]);$db->prepare("UPDATE mesas SET estado='libre' WHERE id=?")->execute([$mesaId]);
    $db->commit();storeDocument('factura',(int)$invoiceId,$invoiceNumber,$invoicePath);storeDocument('comprobante',(int)$receiptId,$receiptNumber,$receiptPath);header('Location: '.url('recepcion/ordenes.php?mesa='.$mesaId.'&documento='.$receiptId));exit;
   }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$msg='No se pudo cerrar la mesa: '.$e->getMessage();}
  }
 }
}
$items=[];if($comanda){$s=$db->prepare('SELECT d.*,p.nombre FROM comanda_detalles d JOIN platos p ON p.id=d.plato_id WHERE d.comanda_id=? ORDER BY d.id');$s->execute([$comanda['id']]);$items=$s->fetchAll();}$total=0.0;foreach($items as $i)$total+=(float)$i['cantidad']*(float)$i['precio_unitario'];
$products=$db->query('SELECT p.*,c.nombre categoria FROM platos p JOIN categorias c ON c.id=p.categoria_id WHERE p.activo=1 ORDER BY c.orden,c.nombre,p.nombre')->fetchAll();
?>
<?php if(isset($_GET['documento'])): $docId=(int)$_GET['documento']; $ds=$db->prepare('SELECT numero FROM facturas WHERE id=?'); $ds->execute([$docId]); $doc=$ds->fetch(); if($doc): ?>
<div class="notice" style="margin-bottom:14px">Documento <?=h($doc['numero'])?> generado correctamente. <button type="button" class="btn olive" id="openGenerated">Abrir comprobante</button></div>
<div id="generatedModal" class="doc-modal open" aria-hidden="false"><div class="doc-modal-box"><div class="actions" style="justify-content:space-between;align-items:center"><strong>Comprobante generado</strong><a class="btn gold" href="<?=url('admin/documentos.php?doc='.$docId.'&mode=download')?>">Descargar</a><button type="button" class="btn danger" id="closeGenerated">Cerrar</button></div><iframe src="<?=url('admin/documentos.php?doc='.$docId.'&mode=view')?>" title="Comprobante"></iframe></div></div>
<style>.doc-modal{display:none;position:fixed;inset:0;background:rgba(0,0,0,.78);z-index:9999;padding:4vh 4vw}.doc-modal.open{display:block}.doc-modal-box{height:92vh;background:#fff;border-radius:14px;overflow:hidden;display:flex;flex-direction:column}.doc-modal-box .actions{padding:10px 14px;background:#1b1b1b;color:#fff}.doc-modal iframe{border:0;flex:1;width:100%;background:#fff}</style>
<script>document.getElementById('closeGenerated').onclick=function(){document.getElementById('generatedModal').classList.remove('open')};</script>
<?php endif; endif; ?>
<div class="card"><h1>Mesa <?=$mesa['numero']?></h1><?php if($msg):?><div class="notice <?=strpos($msg,'No se')===0?'error':''?>"><?=h($msg)?></div><?php endif;?><?php if(!$comanda):?><form method="post"><input type="hidden" name="abrir" value="1"><button class="btn gold">Abrir comanda</button></form><?php else:?><div class="notice">Comanda #<?=$comanda['id']?> abierta desde <?=h($comanda['fecha_apertura'])?></div><div class="grid grid-2"><div><h2>Añadir consumo</h2><form method="post"><input type="hidden" name="add" value="1"><label>Producto</label><select name="plato_id" required><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=h($p['nombre'])?> · <?=money($p['precio_cup'])?></option><?php endforeach;?></select><label>Cantidad</label><input type="number" step="0.01" min="0.01" value="1" name="cantidad"><label>Notas</label><input name="notas" placeholder="Sin cebolla, etc."><button class="btn olive" style="margin-top:10px">Añadir a la mesa</button></form></div><div><h2>Consumo actual</h2><div class="table-wrap"><table><tr><th>Producto</th><th>Cant.</th><th>Subtotal</th></tr><?php foreach($items as $i):?><tr><td><?=h($i['nombre'])?></td><td><?=$i['cantidad']?></td><td class="gold"><?=money((float)$i['cantidad']*(float)$i['precio_unitario'])?></td></tr><?php endforeach;?><tr><th colspan="2">TOTAL</th><th class="gold"><?=money($total)?></th></tr></table></div><?php if($total>0):?><form method="post" style="margin-top:12px"><input type="hidden" name="cobrar" value="1"><label>Método de pago</label><select name="metodo"><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option></select><label>Moneda recibida</label><select name="moneda"><?php foreach(availableCurrencies() as $c=>$n):?><option value="<?=$c?>"><?=$c?></option><?php endforeach;?></select><label>Monto recibido</label><input type="text" inputmode="decimal" name="monto" placeholder="Ej.: 7000 o 7.000" required><small class="muted">En efectivo puede recibir más que el total; RESpos calculará el vuelto.</small><label>Referencia de transferencia</label><input name="referencia"><div class="notice" style="margin-top:10px">Total a cobrar: <b><?=money((float)$total)?></b>. Si recibe efectivo superior al total, el vuelto se calcula automáticamente.</div><button class="btn gold" style="margin-top:10px;width:100%">Cobrar, cerrar mesa y generar documentos PDF</button></form><?php endif;?></div></div><?php endif;?></div><?php require_once __DIR__.'/../includes/footer.php';?>
