<?php
require_once __DIR__ . '/../config/app.php';
require_once __DIR__ . '/../config/database.php';
function initializeRESposDatabase(): void {
    $db=getDBConnection();
    $sql=[
    "CREATE TABLE IF NOT EXISTS usuarios(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password TEXT NOT NULL,nombre TEXT NOT NULL,rol TEXT NOT NULL CHECK(rol IN('admin','economia','recepcion')),activo INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)",
    "CREATE TABLE IF NOT EXISTS configuracion(id INTEGER PRIMARY KEY CHECK(id=1),nombre_restaurante TEXT NOT NULL DEFAULT 'RESpos Restaurant',direccion TEXT,telefonos TEXT,redes_sociales TEXT,sitio_web TEXT,logo_path TEXT,logo_pdf_path TEXT,moneda_principal TEXT NOT NULL DEFAULT 'CUP',tasa_usd REAL NOT NULL DEFAULT 1,tasa_eur REAL NOT NULL DEFAULT 1,tasa_jpy REAL NOT NULL DEFAULT 1,tasa_mxn REAL NOT NULL DEFAULT 1,total_mesas INTEGER NOT NULL DEFAULT 10,updated_at TEXT)",
    "CREATE TABLE IF NOT EXISTS categorias(id INTEGER PRIMARY KEY AUTOINCREMENT,nombre TEXT UNIQUE NOT NULL,orden INTEGER NOT NULL DEFAULT 0,activa INTEGER NOT NULL DEFAULT 1)",
    "CREATE TABLE IF NOT EXISTS platos(id INTEGER PRIMARY KEY AUTOINCREMENT,categoria_id INTEGER NOT NULL,nombre TEXT NOT NULL,descripcion TEXT,ingredientes TEXT,guarniciones TEXT,precio_cup REAL NOT NULL DEFAULT 0,foto_path TEXT,activo INTEGER NOT NULL DEFAULT 1,updated_at TEXT,FOREIGN KEY(categoria_id) REFERENCES categorias(id))",
    "CREATE TABLE IF NOT EXISTS empleados(id INTEGER PRIMARY KEY AUTOINCREMENT,nombre TEXT NOT NULL,apellidos TEXT NOT NULL,ci TEXT UNIQUE NOT NULL,foto_path TEXT,direccion TEXT,telefono TEXT,puesto TEXT NOT NULL,salario REAL NOT NULL DEFAULT 0,activo INTEGER NOT NULL DEFAULT 1)",
    "CREATE TABLE IF NOT EXISTS mesas(id INTEGER PRIMARY KEY AUTOINCREMENT,numero INTEGER UNIQUE NOT NULL,nombre TEXT,capacidad INTEGER NOT NULL DEFAULT 4,estado TEXT NOT NULL DEFAULT 'libre' CHECK(estado IN('libre','ocupada','reservada')),activa INTEGER NOT NULL DEFAULT 1)",
    "CREATE TABLE IF NOT EXISTS reservas(id INTEGER PRIMARY KEY AUTOINCREMENT,cliente_nombre TEXT NOT NULL,cliente_apellidos TEXT,cliente_telefono TEXT,cliente_ci TEXT,mesa_id INTEGER NOT NULL,fecha_hora TEXT NOT NULL,personas INTEGER NOT NULL DEFAULT 1,notas TEXT,estado TEXT NOT NULL DEFAULT 'pendiente' CHECK(estado IN('pendiente','confirmada','atendida','cancelada')),created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(mesa_id) REFERENCES mesas(id),FOREIGN KEY(created_by) REFERENCES usuarios(id))",
    "CREATE TABLE IF NOT EXISTS comandas(id INTEGER PRIMARY KEY AUTOINCREMENT,mesa_id INTEGER NOT NULL,estado TEXT NOT NULL DEFAULT 'abierta' CHECK(estado IN('abierta','pagada','cancelada')),fecha_apertura TEXT NOT NULL,fecha_cierre TEXT,usuario_apertura INTEGER,usuario_cierre INTEGER,FOREIGN KEY(mesa_id) REFERENCES mesas(id))",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_comanda_abierta_mesa ON comandas(mesa_id) WHERE estado='abierta'",
    "CREATE TABLE IF NOT EXISTS comanda_detalles(id INTEGER PRIMARY KEY AUTOINCREMENT,comanda_id INTEGER NOT NULL,plato_id INTEGER NOT NULL,cantidad REAL NOT NULL,precio_unitario REAL NOT NULL,notas TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(comanda_id) REFERENCES comandas(id) ON DELETE CASCADE,FOREIGN KEY(plato_id) REFERENCES platos(id))",
    "CREATE TABLE IF NOT EXISTS facturas(id INTEGER PRIMARY KEY AUTOINCREMENT,numero TEXT UNIQUE NOT NULL,comanda_id INTEGER,tipo TEXT NOT NULL CHECK(tipo IN('factura','comprobante','cierre_caja','inventario','reporte')),monto_total_cup REAL NOT NULL DEFAULT 0,moneda TEXT NOT NULL DEFAULT 'CUP',monto_moneda REAL NOT NULL DEFAULT 0,metodo_pago TEXT,estado TEXT NOT NULL DEFAULT 'emitida',pdf_path TEXT,fecha TEXT NOT NULL,usuario_id INTEGER,FOREIGN KEY(comanda_id) REFERENCES comandas(id))",
    "CREATE TABLE IF NOT EXISTS pagos(id INTEGER PRIMARY KEY AUTOINCREMENT,factura_id INTEGER NOT NULL,metodo TEXT NOT NULL CHECK(metodo IN('efectivo','transferencia')),moneda TEXT NOT NULL DEFAULT 'CUP',monto REAL NOT NULL,monto_cup REAL NOT NULL,referencia TEXT,fecha TEXT NOT NULL,usuario_id INTEGER,FOREIGN KEY(factura_id) REFERENCES facturas(id))",
    "CREATE TABLE IF NOT EXISTS cajas(id INTEGER PRIMARY KEY AUTOINCREMENT,fecha TEXT NOT NULL,usuario_apertura INTEGER,apertura_cup REAL NOT NULL DEFAULT 0,estado TEXT NOT NULL DEFAULT 'abierta' CHECK(estado IN('abierta','cerrada')),fecha_cierre TEXT,usuario_cierre INTEGER,efectivo_esperado REAL,efectivo_declarado REAL,diferencia REAL,pdf_path TEXT)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_caja_abierta_fecha ON cajas(fecha) WHERE estado='abierta'",
    "CREATE TABLE IF NOT EXISTS movimientos_caja(id INTEGER PRIMARY KEY AUTOINCREMENT,caja_id INTEGER NOT NULL,tipo TEXT NOT NULL CHECK(tipo IN('venta','entrada','salida','ajuste')),concepto TEXT NOT NULL,monto_cup REAL NOT NULL,fecha TEXT NOT NULL,usuario_id INTEGER,FOREIGN KEY(caja_id) REFERENCES cajas(id))",
    "CREATE TABLE IF NOT EXISTS insumos(id INTEGER PRIMARY KEY AUTOINCREMENT,nombre TEXT NOT NULL,unidad_medida TEXT NOT NULL,stock_actual REAL NOT NULL DEFAULT 0,stock_minimo REAL NOT NULL DEFAULT 0,precio_compra_unidad REAL NOT NULL DEFAULT 0,codigo TEXT,activo INTEGER NOT NULL DEFAULT 1,updated_at TEXT)",
    "CREATE TABLE IF NOT EXISTS compras(id INTEGER PRIMARY KEY AUTOINCREMENT,numero TEXT UNIQUE NOT NULL,proveedor TEXT,fecha TEXT NOT NULL,total_cup REAL NOT NULL DEFAULT 0,notas TEXT,pdf_path TEXT,usuario_id INTEGER)",
    "CREATE TABLE IF NOT EXISTS compra_detalles(id INTEGER PRIMARY KEY AUTOINCREMENT,compra_id INTEGER NOT NULL,insumo_id INTEGER NOT NULL,cantidad REAL NOT NULL,precio_unitario REAL NOT NULL,subtotal REAL NOT NULL,FOREIGN KEY(compra_id) REFERENCES compras(id) ON DELETE CASCADE,FOREIGN KEY(insumo_id) REFERENCES insumos(id))",
    "CREATE TABLE IF NOT EXISTS movimientos_almacen(id INTEGER PRIMARY KEY AUTOINCREMENT,insumo_id INTEGER NOT NULL,tipo TEXT NOT NULL CHECK(tipo IN('entrada','despacho','ajuste')),cantidad REAL NOT NULL,precio_unitario REAL NOT NULL DEFAULT 0,concepto TEXT,fecha TEXT NOT NULL,usuario_id INTEGER,FOREIGN KEY(insumo_id) REFERENCES insumos(id))",
    "CREATE TABLE IF NOT EXISTS banco_cuentas(id INTEGER PRIMARY KEY AUTOINCREMENT,nombre TEXT NOT NULL,banco TEXT,numero TEXT,saldo_cup REAL NOT NULL DEFAULT 0,activa INTEGER NOT NULL DEFAULT 1)",
    "CREATE TABLE IF NOT EXISTS banco_movimientos(id INTEGER PRIMARY KEY AUTOINCREMENT,cuenta_id INTEGER NOT NULL,tipo TEXT NOT NULL CHECK(tipo IN('entrada','salida')),concepto TEXT NOT NULL,monto_cup REAL NOT NULL,referencia TEXT,fecha TEXT NOT NULL,usuario_id INTEGER,FOREIGN KEY(cuenta_id) REFERENCES banco_cuentas(id))",
    "CREATE TABLE IF NOT EXISTS documentos(id INTEGER PRIMARY KEY AUTOINCREMENT,tipo TEXT NOT NULL,referencia_id INTEGER,numero TEXT,nombre_archivo TEXT NOT NULL,ruta TEXT NOT NULL,fecha TEXT NOT NULL,usuario_id INTEGER)",
    "CREATE TABLE IF NOT EXISTS auditoria(id INTEGER PRIMARY KEY AUTOINCREMENT,usuario_id INTEGER,accion TEXT NOT NULL,detalle TEXT,fecha TEXT NOT NULL,FOREIGN KEY(usuario_id) REFERENCES usuarios(id))",
    "CREATE TABLE IF NOT EXISTS producto_insumos(id INTEGER PRIMARY KEY AUTOINCREMENT,plato_id INTEGER NOT NULL,insumo_id INTEGER NOT NULL,cantidad REAL NOT NULL,FOREIGN KEY(plato_id) REFERENCES platos(id) ON DELETE CASCADE,FOREIGN KEY(insumo_id) REFERENCES insumos(id))"
    ];
    foreach($sql as $q) $db->exec($q);
    $db->exec("INSERT OR IGNORE INTO configuracion(id,nombre_restaurante,direccion,telefonos,redes_sociales,sitio_web,logo_path,logo_pdf_path,moneda_principal,total_mesas,updated_at) VALUES(1,'RESpos Restaurant','','','','','assets/uploads/logo.png','assets/uploads/logo.jpg','CUP',10,datetime('now'))");
    $cats=['Entrantes','Sopas y Cremas','Ensaladas','Platos Fuertes','Especialidades de la Casa','Guarniciones','Postres','Bebidas','Cócteles','Vinos','Cervezas','Cafetería','Desayunos','Menú Infantil'];
    $i=0; foreach($cats as $cat){$s=$db->prepare('INSERT OR IGNORE INTO categorias(nombre,orden) VALUES(?,?)');$s->execute([$cat,$i++]);}
    $s=$db->prepare('INSERT OR IGNORE INTO usuarios(id,username,password,nombre,rol) VALUES(1,?,?,?,?)');$s->execute(['admin',password_hash('admin123',PASSWORD_DEFAULT),'Administrador Principal','admin']);
    $n=(int)$db->query('SELECT COUNT(*) FROM mesas')->fetchColumn(); if($n===0){$ins=$db->prepare('INSERT INTO mesas(numero,nombre,capacidad) VALUES(?,?,?)');for($i=1;$i<=10;$i++)$ins->execute([$i,'Mesa '.$i,4]);}
    foreach(['Efectivo CUP','Cuenta bancaria principal'] as $name){$s=$db->prepare('SELECT COUNT(*) FROM banco_cuentas WHERE nombre=?');$s->execute([$name]); if(!$s->fetchColumn() && $name!=='Efectivo CUP'){$s=$db->prepare('INSERT INTO banco_cuentas(nombre,banco,numero) VALUES(?,?,?)');$s->execute([$name,'','']);}}
}
if (basename(__FILE__) === basename($_SERVER['SCRIPT_FILENAME'] ?? '')) { initializeRESposDatabase(); echo 'RESpos: base de datos SQLite inicializada.'; }
?>
