<?php
require_once __DIR__.'/../includes/header.php'; checkAuth(['admin']);
$db=getDBConnection(); $msg=''; $err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  $a=$_POST['action']??'';
  if($a==='create'){$s=$db->prepare('INSERT INTO usuarios(username,password,nombre,rol) VALUES(?,?,?,?)');$s->execute([trim($_POST['username']),password_hash($_POST['password'],PASSWORD_DEFAULT),trim($_POST['nombre']),$_POST['rol']]);$msg='Usuario creado.';}
  elseif($a==='toggle'){$db->prepare('UPDATE usuarios SET activo=1-activo WHERE id<>1 AND id=?')->execute([(int)$_POST['id']]);$msg='Estado actualizado.';}
  elseif($a==='role'){$db->prepare('UPDATE usuarios SET rol=? WHERE id<>1 AND id=?')->execute([$_POST['rol'],(int)$_POST['id']]);$msg='Rol actualizado.';}
  elseif($a==='password'){$db->prepare('UPDATE usuarios SET password=? WHERE id=?')->execute([password_hash($_POST['password'],PASSWORD_DEFAULT),(int)$_POST['id']]);$msg='Contraseña actualizada.';}
  elseif($a==='delete'){$db->prepare('DELETE FROM usuarios WHERE id<>1 AND id=?')->execute([(int)$_POST['id']]);$msg='Usuario eliminado.';}
 }catch(Throwable $e){$err='No se pudo completar la operación. Revisa que el usuario no exista ya.';}
}
$users=$db->query('SELECT id,username,nombre,rol,activo,created_at FROM usuarios ORDER BY id')->fetchAll();
?>
<div class="grid grid-2">
<div class="card"><h1>Usuarios del sistema</h1><p class="muted">Admin controla las tres áreas: administración, economía y recepción.</p><?php if($msg):?><div class="notice"><?=h($msg)?></div><?php endif;?><?php if($err):?><div class="notice error"><?=h($err)?></div><?php endif;?><form method="post" class="form-grid"><input type="hidden" name="action" value="create"><div><label>Nombre</label><input name="nombre" required></div><div><label>Usuario</label><input name="username" required></div><div><label>Contraseña</label><input type="password" name="password" minlength="6" required></div><div><label>Rol</label><select name="rol"><option value="economia">Economía</option><option value="recepcion">Recepción</option><option value="admin">Administrador</option></select></div><div class="full"><button class="btn gold">Crear usuario</button></div></form></div>
<div class="card"><h2>Usuarios existentes</h2><div class="table-wrap"><table><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th>Gestión</th></tr><?php foreach($users as $u):?><tr><td><b><?=h($u['nombre'])?></b><br><span class="muted">@<?=h($u['username'])?></span></td><td><?=strtoupper(h($u['rol']))?></td><td><?=$u['activo']?'Activo':'Inactivo'?></td><td><form method="post" class="actions"><input type="hidden" name="action" value="password"><input type="hidden" name="id" value="<?=$u['id']?>"><input type="password" name="password" minlength="6" placeholder="Nueva clave" required><button class="btn">Cambiar clave</button></form><?php if($u['id']==1):?><span class="badge">Administrador principal · no se elimina</span><?php else:?><form method="post" class="actions"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="btn <?= $u['activo']?'danger':'olive'?>"><?=$u['activo']?'Desactivar':'Activar'?></button></form><form method="post" class="actions" style="margin-top:6px"><input type="hidden" name="action" value="role"><input type="hidden" name="id" value="<?=$u['id']?>"><select name="rol"><option value="admin" <?=$u['rol']==='admin'?'selected':''?>>Admin</option><option value="economia" <?=$u['rol']==='economia'?'selected':''?>>Economía</option><option value="recepcion" <?=$u['rol']==='recepcion'?'selected':''?>>Recepción</option></select><button class="btn">Cambiar rol</button></form><form method="post" style="margin-top:6px"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="btn danger" data-confirm="¿Eliminar definitivamente este usuario?">Eliminar</button></form><?php endif;?></td></tr><?php endforeach;?></table></div></div></div>
<?php require_once __DIR__.'/../includes/footer.php';?>
